// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7AZd7LbD2jaoD_DXU-NjqL6SD9KRjzjs',
    appId: '1:129535961363:web:59332ed3310478a28652e6',
    messagingSenderId: '129535961363',
    projectId: 'whatthefood-app-1bdfe',
    authDomain: 'whatthefood-app-1bdfe.firebaseapp.com',
    storageBucket: 'whatthefood-app-1bdfe.appspot.com',
    measurementId: 'G-WJR1GJ8BB2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQcc5b-bpy-3PaEH89JTbfpQTXow9XWts',
    appId: '1:129535961363:android:4e5df377855ca28c8652e6',
    messagingSenderId: '129535961363',
    projectId: 'whatthefood-app-1bdfe',
    storageBucket: 'whatthefood-app-1bdfe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG9Zg8NS_nzUTyM3R5xCNiD1ncx6JsdxI',
    appId: '1:129535961363:ios:0c8725350f5739478652e6',
    messagingSenderId: '129535961363',
    projectId: 'whatthefood-app-1bdfe',
    storageBucket: 'whatthefood-app-1bdfe.appspot.com',
    iosBundleId: 'com.example.wtfeua',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG9Zg8NS_nzUTyM3R5xCNiD1ncx6JsdxI',
    appId: '1:129535961363:ios:0c8725350f5739478652e6',
    messagingSenderId: '129535961363',
    projectId: 'whatthefood-app-1bdfe',
    storageBucket: 'whatthefood-app-1bdfe.appspot.com',
    iosBundleId: 'com.example.wtfeua',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7AZd7LbD2jaoD_DXU-NjqL6SD9KRjzjs',
    appId: '1:129535961363:web:853d611a060121658652e6',
    messagingSenderId: '129535961363',
    projectId: 'whatthefood-app-1bdfe',
    authDomain: 'whatthefood-app-1bdfe.firebaseapp.com',
    storageBucket: 'whatthefood-app-1bdfe.appspot.com',
    measurementId: 'G-8HPTZYT2HN',
  );
}
